-- Create soil_measurements table
CREATE TABLE IF NOT EXISTS public.soil_measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nitrogen FLOAT,
    phosphorus FLOAT,
    potassium FLOAT,
    ph FLOAT,
    temperature FLOAT,
    moisture FLOAT,
    measured_at TIMESTAMPTZ DEFAULT NOW(),
    device_id TEXT,
    location TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for faster lookups by device_id and date
CREATE INDEX IF NOT EXISTS idx_soil_measurements_device_id ON public.soil_measurements(device_id);
CREATE INDEX IF NOT EXISTS idx_soil_measurements_measured_at ON public.soil_measurements(measured_at);

-- Enable Row Level Security
ALTER TABLE public.soil_measurements ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access (adjust based on your security needs)
CREATE POLICY "Allow public read access" 
ON public.soil_measurements 
FOR SELECT 
USING (true);

-- Create policy to allow insert with API key (handled by your application)
CREATE POLICY "Allow insert with API key" 
ON public.soil_measurements 
FOR INSERT 
WITH CHECK (true);
